### ISSUE TITLE
Error: 'No humans in first frame' for provided examples

### ISSUE THREAD

**Issue by Kamlesh364** [hmchuong/MaGGIe#7]
I'm running the demo app implemented in Gardio. I am using the given examples only as input files but it works only on images and not on videos.

![image](https://github.com/user-attachments/assets/1e18c7b8-bb93-4d61-9d30-ab6e6232c3c8)

Terminal errors are as following-

```
Traceback (most recent call last):
  File "/home/kamlesh/.local/lib/python3.8/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/kamlesh/.local/lib/python3.8/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/kamlesh/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/kamlesh/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/kamlesh/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/kamlesh/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 2364, in run_sync_in_worker_thread
    return await future
  File "/home/kamlesh/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "/home/kamlesh/.local/lib/python3.8/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/home/kamlesh/MaGGIe/demo/app.py", line 39, in inference_video
    raise gr.Error("No person detected, please try video with visible human in the first frame!")
gradio.exceptions.Error: 'No person detected, please try video with visible human in the first frame!'
```

**Comment by hmchuong** [comment]
Hi, the demo requires the first frame to have visible people. There may be some problems with the human segmentation model that cannot detect people. I cannot fix it right now due to a deadline coming up. I will fix it later.

**Comment by hmchuong** [comment]
I updated the demo and now supporting [Samurai](https://github.com/educelab/samurai). All examples work fine, let me know if you still faces the problem.
